name: CI-SFTP

on:
    push:
        branches: [main]
    workflow_dispatch:
jobs:
    deploy-via-sftp:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: SFTP Deploy
              uses: wlixcc/SFTP-Deploy-Action@v1.2.1
              with:
                  username: root
                  server: 165.232.179.34
                  port: 22 # default is 22
                  ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

                  local_path: ./* # default is ./*
                  remote_path: /root/Nimo-Music/

                  args: "-o ConnectTimeout=5"
